[package]
name = "roseplayer_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
gstreamer = "0.22.6"
gstreamer-player = "0.22.6"
glib = "0.19.9"
reqwest = { version = "0.12.5", features = ["json"] }
tokio = { version = "1.38.0", features = ["macros", "sync", "rt", "rt-multi-thread", "time", "signal"] }
serde = { version = "1.0.203", features = ["serde_derive"] }
serde_json = "1.0.118"
thiserror = "1.0.61"
ratatui = "0.27.0"
log = "0.4.22"
env_logger = "0.11.3"
flexi_logger = "0.28.5"
toml = "0.8.14"
rusqlite = "0.31.0"